@echo off
echo Starting QuickTrip Frontend...
cd /d "c:\Users\deysa\OneDrive\Desktop\QuickTrip\client"
echo Installing dependencies...
npm install
echo Starting development server...
npm run dev
pause
